version: '3'

# Variables defined in .env file

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    labels:
      description: "Portainer: Web interface to manage docker containers"
      system: true
    volumes:
    - /data/docker/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"
    networks:
    - frontend
    restart: always

networks:
  backend:
  frontend:
    driver: bridge

