version: '3'

# Variables defined in .env file

services:

  portainer:
    container_name: portainer
    image: portainer/portainer
    labels:
      description: "Portainer: Web interface to manage docker containers"
      system: true
    volumes:
    - /data/docker/portainer:/data
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - "9000:9000"
    networks:
    - frontend
    restart: always
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  backend:
  frontend:
    driver: bridge

